### ISSUE TITLE
run on Zalando Kubernetes setup

### ISSUE THREAD

**Issue by lotharschulz** [zalando/ghe-backup#55]
run ghe-backup on Zalando Kubernetes cluster:

- [x] create docker images for Kubernetes cluster: #66
- [x] deploy to Kubernetes cluster: #74 
- [x] gather experience running it in production

**Comment by lotharschulz** [comment]
`kubectl exec -it [pod] bash`

```
/var/log$ more ghe-prod-backup.log
Starting backup of github-master.bus.zalan.do in snapshot 20171212T135025
Connect github-master.bus.zalan.do:122 OK (v2.11.6)
Backing up GitHub settings ...
Backing up SSH authorized keys ...
Backing up SSH host keys ...
Backing up MySQL database ...
Backing up Redis database ...
Backing up audit log ...
Backing up hookshot logs ...
Backing up Git repositories ...
```

this is also visible on logs aggregator:

<img width="981" alt="screen shot 2017-12-12 at 15 25 10" src="https://user-images.githubusercontent.com/1148268/33889646-133b51e6-df51-11e7-9306-fa62f48e5caf.png">

**Comment by lotharschulz** [comment]
describing pod showed once:

`  6m		6m		1	kubelet, ip-XX-X-XX-XXX.eu-central-1.compute.internal	spec.containers{container-ghe-backup}	Warning		Failed			Error: context deadline exceeded`

solution: 
- delete sts, po, pvc, pv
- redeploy

result:

```
$ (z)kubectl logs -l application=ghe-backup
Backing up Git repositories ...
Backing up GitHub Pages ...
Backing up asset attachments ...
Backing up storage data ...
Backing up hook deliveries ...
Backing up custom Git hooks ...
Backing up Elasticsearch indices ...
Completed backup of xxxxxxx:122 in snapshot 20171212T171301 at 19:22:42
Checking for leaked ssh keys ...
* No leaked keys found
```

**Comment by lotharschulz** [comment]
related: https://github.com/zalando/ghe-backup/pull/80
